### ISSUE TITLE
Problem parsing agda response from C-c C-l

### ISSUE THREAD

**Issue by pdelano** [banacorn/agda-mode#101]
I'm having a problem when I try to check my agda file in an Atom tab with C-c C-l.

Agda mode seems to be working, because the Unicode characters are rendered correctly, and I see "Agda" in the information in the lower right of the Atom window when a tab holding an Agda file has the focus.  Also, agda seems to be working correctly when I execute "agda myfile.agda" from the command line.

I get something like the following in a horizontal window at the bottom of my editor screen:

    1 errors arisen when trying to parse the following text responses from agda:

    ["agda2-highlight-add-annotations", ["1", "7", ["keyword"], "nil"], ["8", "16", ["module"], "nil", ...

    and so on ...

I'm running:
  Ubuntu 18.04.01 LTS
  Agda 2.6.0.1
  Agda stdlib-1.0.1
  Atom 1.34.0 x64
  agda-mode 0.9.0
  language-agda 1.0.9

For what it's worth, agda-mode in emacs seems to be working correctly so it's probably not an Agda problem, but I don't want to use emacs.

**Comment by banacorn** [comment]
Hey Patrick! Nice to see you here!
I think I've found the problem, the patch should be coming soon!

**Comment by banacorn** [comment]
Please reopen this issue if the problem persists

**Comment by pdelano** [comment]
I hope I updated agda-mode properly - I'm running agda-mode 0.9.1 now.  Everything else is the same.

C-c C-l still seems not to be working, but the behavior has changed.  Whereas before if I had an Agda file that didn't parse correctly, I'd see a bunch of lines of text that might be Json lists with the error messages from Adga.  Now I always see just the same single message:
    1 errors arisen when trying to parse the following text responses from agda:

    ["agda2-highlight-add-annotations"]

**Comment by pdelano** [comment]
From what I've read, I can't actually reopen an issue that was closed by a
repo owner or collaborator.  I don't know how to do it except to open
another issue and reference this one - which doesn't seem to be quite the
thing.

I'm still seeing a problem, so I just posted a comment on the original
issue.

**Comment by banacorn** [comment]
Sorry about that.
I've released `v0.9.3` just now, which fixed some parsing problems in #98 and Windows.
It may also be related to this issue.
Please upgrade to `v0.9.3` and see if the problem's still there. 
If so, please provide us with a Agda file for reproducing the issue.

**Comment by pdelano** [comment]
No, I'm using agda-mode 0.9.3 now, and I'm still seeing the same error on C-c C-l 
  Parse Error
     1 errors arisen when trying to parse the following text responses from agda:

     ["agda2-highlight-add-annotations"]

I see the same error on _every_ Agda file I've tried, but here's one for example

module plfa.ExBin where

import Relation.Binary.PropositionalEquality as Eq
open Eq using (_≡_; refl)
open Eq.≡-Reasoning using (begin_; _≡⟨⟩_; _∎)
open import Data.Nat using (ℕ; zero; suc; _+_; _*_; _∸_)

data Bin : Set where
  nil : Bin
  x0_ : Bin → Bin
  x1_ : Bin → Bin

**Comment by banacorn** [comment]
I'm implementing some kind of parse dump, so that I could have better diagnostic of the issue, because I can't seem to reproduce it yet.

**Comment by pdelano** [comment]
I much appreciate your efforts.  Very possibly I have some user error in my setup, but if I do I don't know how to go about finding it.

**Comment by banacorn** [comment]
You should see a big button when there's parse error since `v0.9.4`.
Please press the button and paste the generated log here :D

Meanwhile, perhaps go to `Settings > Packages > Agda Mode > Settings` and change **Highlighting information passing** from **Direct** to **Indirect** might will help (by telling Agda to hush)
![Image of settings](https://i.imgur.com/0ntqeX4.png)

Sorry for the inconvenience!

**Comment by banacorn** [comment]
Fixed in `v0.9.5`
